# Generated by Django 5.0.6 on 2024-05-29 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carz', '0001_initial'),
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealerships.dealership'),
        ),
    ]
