# Generated by Django 5.0.6 on 2024-05-29 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bike_dealership'),
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='dealership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dealerships.dealership'),
        ),
    ]
